# Generated by Django 3.2.15 on 2022-08-06 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense_category_tbl',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('expense_category', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User_details_tbl',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Expense_summary_tbl',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Discription', models.CharField(max_length=200)),
                ('Amount', models.FloatField()),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.expense_category_tbl')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user_details_tbl')),
            ],
        ),
    ]
