# Generated by Django 3.2.15 on 2022-08-06 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_expense_category_tbl_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense_category_tbl',
            name='color',
        ),
    ]
