# Generated by Django 3.2.15 on 2022-08-06 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_expense_category_tbl_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense_category_tbl',
            name='color',
            field=models.CharField(default='#008000', max_length=20),
        ),
    ]
