# Generated by Django 3.2.15 on 2022-08-07 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_expense_category_tbl_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense_summary_tbl',
            name='expense_category',
            field=models.CharField(default='not specified', max_length=200),
            preserve_default=False,
        ),
    ]
